server:
  port: 8030
spring:
  application:
    name: getway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 给服务提供者provider设置映射
zuul:
  routes:
    provider: /p/**