server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
#    配置文件的获取方式 native:本地
  profiles:
    active: native
#  配置文件存放的路径
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared